"""empty message

Revision ID: aca581c68704
Revises: 3c6161e26fd9
Create Date: 2023-01-13 09:58:51.893496

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aca581c68704'
down_revision = '3c6161e26fd9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('seat', schema=None) as batch_op:
        batch_op.alter_column('student_name',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('seat', schema=None) as batch_op:
        batch_op.alter_column('student_name',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)

    # ### end Alembic commands ###
